basic_keywords:
  - 'keyboard switch'
  - 'keyboard switches'
  - 'mechanical switch'
  - 'cherry mx'
  - gateron
  - kailh
  - 'nk creams'
  - 'holy panda'
  - kbdfans
  - 'mx switches'
  - 'mx switch'
  - keyboards
  - keyboard
  - typing
  - typist
  - frankenswitch
  - frankenswitches
